- name: Upload Release Notes to Wiki
  uses: docker://decathlon/wiki-page-creator-action:2.0.1
  env:
    GH_PAT: ${{ secrets.GH_PAT }}
    ACTION_MAIL: daniel.salgado.rojo@gmail.com
    ACTION_NAME: dsalgador
    OWNER: dsalgador
    REPO_NAME: wiki-github
